import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-4 border-b mb-8 bg-gray-100 dis">
          <h1 className={`${geistSans.variable} font-sans`}>My App</h1>
        </header>
        <section className="p-4">
          {children}
        </section>
        <footer className="p-4 border-t mt-8 bg-gray-100 text-center">
          <p className={`${geistMono.variable} font-mono text-sm`}>
            &copy; 2025 My App
          </p>
        </footer>
      </body>
    </html>
  );
}
